### ISSUE TITLE
Simple Upload Question

### ISSUE THREAD

**Issue by chr0m1ng** [CrossGeeks/FileUploaderPlugin#1]
Hi, i'm kind of new on Xamarin World and I'm confused about how to use this API. My FileZilla server is running on LAN and i'm putting the URL as "ftp://192.168.0.104:21". So, I need to login, cause I'm not allowing anonymous login, where am I suposed  to put my login credentials?

I tried to do something like:
`CrossFileUploader.Current.UploadFileAsync("ftp://192.168.0.104:21", new FilePathItem(item.FileName, "storage/emulated/0/Pictures/AAA-6666/1749678.jpg"), new Dictionary<string, string>()
                    {
                        {"user","gabriel"},
                        {"pass", "123"}
                    });`
But i'm getting an strange error, on filezilla I have a lot of syntax error like this: https://imgur.com/a/UPpM5

And the output of the debug on VisualStudio is:
`[0:] -1 - Java.Net.ProtocolException: Unexpected status line: 220-FileZilla Server 0.9.60 beta
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method) [0x00084] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11262 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod) [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/JNIEnv.g.cs:96 
  at OkHttp.Call.Execute () [0x00049] in <be7430e915c648c28d572474c6942401>:0 
  at Plugin.FileUploader.FileUploadManager.MakeRequest (System.String url, System.String tag, OkHttp.MultipartBuilder requestBodyBuilder, System.Collections.Generic.IDictionary`2[TKey,TValue] headers) [0x0009b] in C:\Plugins\FileUploader\src\Plugin.FileUploader.Android\FileUploadManager.cs:208 
  at Plugin.FileUploader.FileUploadManager+<>c__DisplayClass13_0.<UploadFileAsync>b__0 () [0x00089] in C:\Plugins\FileUploader\src\Plugin.FileUploader.Android\FileUploadManager.cs:128 
  --- End of managed Java.Net.ProtocolException stack trace ---
java.net.ProtocolException: Unexpected status line: 220-FileZilla Server 0.9.60 beta
	at com.squareup.okhttp.internal.http.StatusLine.parse(StatusLine.java:54)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:190)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
	at com.squareup.okhttp.Call.getResponse(Call.java:272)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)`

Can someone explain me how to properly use?

**Comment by rdelrosario** [comment]
The plugin currently doesn't support ftp just http uploads for now
